on:
    push:
        paths-ignore:
            - "docs/**"
            - "*.md"
            - "tests/**"
    pull_request:
        paths-ignore:
            - "docs/**"
            - "*.md"
            - "tests/**"
jobs:
  linting:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt -r requirements.txt
      - name: Run tests
        run: |
          "pylint src/ | pylint_report.py > report.html"
      - name: Upload report
        uses: actions/upload-artifact@v1
        with:
          name: pylint-report
          path: report.html